### ISSUE TITLE
Alonzo automation checklist

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#647]
Transaction build scenarios:

Plutus scripts 
  [ ] always-succeeds-spending.plutus
  [ ] custom-guess-42-datum-42.plutus
  [ ] simple-minting-policy.sh
  [ ] stake delegation, withdrawal

Types of redeemers:
  [ ] spend - spending a script utxo entry
  [ ] mint - minting tokens
  [ ] cert - certificates with script credentials
  [ ] reward - reward withdrawals from script addresses

Legacy transaction types:
- [ ] - multi-assets: minting, burning, spending
- [ ] - update proposals
- [ ] - stake pool (registration, de-registration) and stake address certificates (registration, delegation, de-registration) 
- [ ] - MIR certificates
- [ ] - tx with metadata
- [ ] - multi-sig scripts (time locking)

Other scenarios:
- [ ] - 1 tx-in + 1 tx-out + 1 change-address
- [ ] - many tx-in + many tx-out + 1 change-address
- [ ] - no enough funds in tx-in
- [ ] - no enough funds for fees
- [ ] - no existing/valid tx-in
- [ ] - no existing/valid tx-out
- [ ] - no existing/valid change-address
- [ ] - no tx-in
- [ ] - no tx-out
- [ ] - no change-address

Alonzo protocol parameter values:

- [ ] - collateralPercent
- [ ]   - enough funds for 100% collateral but not for 150%
- [ ]   - exact funds for fees
- [ ] - maxCollateralInputs
