### ISSUE TITLE
CIP-40 Collateral outputs

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#998]
**TODO Improvements:**
[1265](https://github.com/input-output-hk/cardano-node-tests/issues/1265)
[1266](https://github.com/input-output-hk/cardano-node-tests/issues/1266)
[1267](https://github.com/input-output-hk/cardano-node-tests/issues/1267)

**cardano-node related PR:**
[#3810](https://github.com/input-output-hk/cardano-node/pull/3810)

_info_
https://github.com/cardano-foundation/CIPs/pull/216/files
https://input-output.atlassian.net/browse/CAD-3415

**AC1** _Possible to define the total collateral amount and the collateral output_
1. Build a tx with: `return-collateral-tx-out`, collateral inputs higher than expected, the right amount on tx-total-collateral; check that only the necessary amount is charged and the change is present on the `return-collateral-tx-out` specified
    - [x] using build
    - [x] using build-raw
2. Build a tx with collateral inputs higher than expected with the same amount on `tx-total-collateral `**without** `return-collateral-tx-out` defined, check that all the collateral are charged.
    - [x] using build
    - [x] using build-raw
3. Build a tx with` tx-total-collateral `different than tx with collateral inputs amount (fails phase1 validation) - **Expect failure PBT**
    - [x] using build
    - [x] using build-raw
4. Build a tx with with collateral inputs higher than expected with `return-collateral-tx-out` defined but **without**  `tx-total-collateral ` defined, check that only the necessary amount is charged and the change is present on the `return-collateral-tx-out` specified
    - [x] using build
    - [x] using build-raw

**AC2** _collateral input can include MA which is returned on validation failure_
1. When the collateral output is provided then collateral input can include MA which is returned on validation failure (the error message should be **meaningful** for the end-user)
    - [x] using build
    - [x] using build-raw
 
**AC3** _Collateral output needs to be balanced_
1. Collateral output needs to be balanced according to `sum(collateral_input) = sum(collateral_output) + collateral_consumed`
    - [x] using build
    - [x] using build-raw

**Comment by james-iohk** [comment]
- Collateral return is not related to HW wallet
- Collateral total is optional and useful for HW wallets
- Collateral return is optional
- When collateral return is not provided then Alonzo-rules apply (e.g. collateral is ada-only)
- When collateral return is provided then collateral input can include MA

**Comment by james-iohk** [comment]
This is probably close enough related https://github.com/cardano-foundation/CIPs/pull/216

**Comment by saratomaz** [comment]
**cardano-node related PR:**
#3810

_info_
https://github.com/cardano-foundation/CIPs/pull/216/files

**AC1** _If transaction phase-2 validation fails the exact collateral amount is charged_
- [ ] Submit a tx with collateral inputs higher than expected, check that only the necessary amount is charged.
- [ ] Submit a tx with less collateral inputs than expected - **Expect failure** _already implemented in previous era_

**AC2** _Possible to define the total collateral amount and the collateral output address_
- [ ] Submit a tx with collateral inputs higher than expected but with the right amount on tx-total-collateral, check that only the necessary amount is charged.
- [ ] Build a tx with tx-total-collateral different than the expected (fails phase1 validation) - **Expect failure PBT**

**Comment by vfrsilva** [comment]
@dorin100 lets please make sure that:
1. If return collateral doesn't satisfy minUtxo constraint, then submit fails phase1 validation
a. Is the error message meaningful?
2. If the collateral total value is incorrect, then submit fails phase1 validation
a. Is the error message meaningful?
